# build_cloud: AWS-us-east-2-t3-medium
image: Visual Studio 2019



environment:
  matrix:
    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python
    - PYTHON: "C:\\Python36-x64"

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

on_finish:
  - ps: >-
      if (Test-Path $env:APPVEYOR_BUILD_FOLDER\test_roundtrip.log){
          Push-AppveyorArtifact test_roundtrip.log
      };
      If ($env:DEBUG -eq $True) {
          $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
      };

init:
  # exit if secure variables are unset (saves time if fired by a non-team pull request)
  - ps: if ($env:GH_SSH_PRIVATE_KEY -eq $null) { exit }

  - git config --global user.name oll-bot
  - git config --global user.email developers@openlawlib.org

install:
  # upgrade pip
  - "%PYTHON%\\python.exe -m pip install --upgrade pip"

  # the only way we can use the deploy key is by putting it in an environment variable (see above)
  # and then using PowerShell (ps) to copy the environment variable into a file (see below)
  # begin/end key lines should be in the environment variable
  - ps: $key = "-----BEGIN RSA PRIVATE KEY-----`n"
  - ps: $key += $env:GH_SSH_PRIVATE_KEY.Replace(" ", "`n")
  - ps: $key += "`n-----END RSA PRIVATE KEY-----`n"
  - ps: Set-Content c:\users\appveyor\.ssh\id_rsa $key
  - set $env:PARTNER'_XML_CODIFIED_PATH'='..\'$env:UPSTREAM'-codified-preview'

before_build:
  - ps: >-
      If ($env:APPVEYOR_SCHEDULED_BUILD -eq $True){
        echo 'Scheduled build. Checking if upstream can be merged';
        git remote add upstream 'https://github.com/'$env:UPSTREAM'.git';
        git fetch upstream;
        git merge upstream/master;
        git diff --name-only --diff-filter=U >> output.log;
        If (-Not [String]::IsNullOrWhiteSpace((Get-content output.log))){
          throw 'Merge with upstream failed. Please update the repository manually';
        }
        else {
          echo 'Upstream changes have been merged.';
          git remote set-url origin git@github.com:$env:APPVEYOR_REPO_NAME'.git';
          
          # read requirements.txt and split it by # to get partners namespace, 
          # example result:  oll.partners.us.ca.cities.san_mateo
          $REQUIREMENTS_CONTENT = Get-Content .\requirements.txt -Raw;
          $CONTENT_ARRAY = $REQUIREMENTS_CONTENT -split "# ";
          $global:PARTNER_NAMESPACE = $CONTENT_ARRAY[1];
          
          $requirementsContent = $REQUIREMENTS_CONTENT;
          $requirementsContent | Set-Content -Path 'requirements.txt';
          git add requirements.txt;
          git commit -m "Reverted requirements.txt update";
          git push origin HEAD:master;
        }
      };

      If ($env:TAF_BRANCH) {
        git clone -q git@github.com:openlawlibrary/taf.git ..\wheels\taf
        git -C ..\wheels\taf checkout -q $env:TAF_BRANCH
        $env:TAF_WHEEL = "-e ..\wheels\taf"
      } else {
        $env:TAF_WHEEL = "taf"
      };

      If ($env:PLATFORM_BRANCH) {
        git clone -q git@github.com:openlawlibrary/platform.git ..\wheels\platform
        git -C ..\wheels\platform checkout -q $env:PLATFORM_BRANCH
        $env:CORE_WHEEL = "-e ..\wheels\platform\core"
        $env:PARTNERS_WHEEL = "-e ..\wheels\platform\partners"
      } else {
        $env:CORE_WHEEL = "--pre oll-core"
        $env:PARTNERS_WHEEL = "--pre oll-partners"
      };

  - "%PYTHON%\\python.exe -m pip -q install wheel"
  - "%PYTHON%\\python.exe -m pip -q install %TAF_WHEEL%"
  - "%PYTHON%\\python.exe -m pip -q install %CORE_WHEEL%"
  - "%PYTHON%\\python.exe -m pip -q install %PARTNERS_WHEEL%"
  - "%PYTHON%\\python.exe -m pip list"

  - "%PYTHON%\\python.exe  -m oll.tools.cli ci clone-repos --library-root .. --xml . "

  # install versioned resources (if and only if the build is a tag or cron build)
  - "%PYTHON%\\python.exe -m pip -q install -r requirements.txt"
  - "%PYTHON%\\python.exe -m pip -q install pytest"
  # print out the git commits for xml repo
  - git -C ..\%UPSTREAM% rev-parse HEAD

  - ps: echo $global:PARTNER_NAMESPACE.tests.docs.code.roundtrip

build_script:
  - ps: $env:FLAG = if ($env:APPVEYOR_PULL_REQUEST_NUMBER -eq $null) { "--deploy" }
  - "%PYTHON%\\python.exe  -m oll.tools.cli ci build-preview --library-root .. --auth ../law %FLAG%"

test_script:
  # run roundtrip tests
  - ps: >-
      if ($env:APPVEYOR_REPO_BRANCH -eq 'master' -Or $env:APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH -eq 'master'){
        cd $env:APPVEYOR_BUILD_FOLDER;
        $run_roundtrip = $env:PYTHON + '\python.exe -m pytest --pyargs ' + $global:PARTNER_NAMESPACE + '.tests.docs.code.roundtrip -m "full_roundtrip"';
        iex $run_roundtrip;
      } else {
        echo "Skipping rountrip tests - not master branch build";
      }
notifications:
  - provider: Slack
    incoming_webhook:
      # post to the fire channel
      secure: KUaR+KAqX1jU0LF7kRDKHHGEAoItFzIHSjcreyRvnrT1vcX5+4iV77Ivysxl8jhh8ocUE0JCcmcKI0xPTb+M+EMfb8xk9L7+XCTdNubjU5w=
    on_build_success: false

artifacts:
  - path: test_roundtrip.log
    name: roundtrip log
